### ISSUE TITLE
how tf we stop this shit

### ISSUE THREAD

**Issue by nostorian** [vroomyy/DiscordMassMention#13]
> i was about to get token locked lol, just left the server, any other ways to stop it?

yea and one more thing how do i make this mentioner send more messages, coz it sends them really slowly should i change the interval value? and is the interval value in seconds or what?

**Comment by Slangy1** [comment]
@Nostorian its not happening to me its fast

**Comment by vroomyy** [comment]
change interval, u can also make it send x amounts of messages and just rerun the script. also this won't phone lock your account
