### ISSUE TITLE
Uncaught ReferenceError: t is not defined

### ISSUE THREAD

**Issue by Ccsmo** [vroomyy/DiscordMassMention#14]
doesnt work anymore is it bcz im doing something wrong? "Uncaught ReferenceError: t is not defined" is the error message

**Comment by abiyphetot** [comment]
@vroomyy

**Comment by abiyphetot** [comment]
might wanna fix the code?

**Comment by abiyphetot** [comment]
@vroomyy

**Comment by abiyphetot** [comment]
@vroomyy bro wake up

**Comment by MinaCat0999** [comment]
@vroomyy

**Comment by MinaCat0999** [comment]
yo!!

**Comment by vroomyy** [comment]
find module is outdated you will have to update it
