### ISSUE TITLE
Send Message As Someone Else

### ISSUE THREAD

**Issue by Minacat1** [vroomyy/DiscordMassMention#4]
I found out there's a glitch on the script it sends messages as someone else but not me I've been trying to figure out what it is if you have a script for this I appreciate it! :)

**Comment by Minacat1** [comment]
@vroomyy

**Comment by vroomyy** [comment]
can you show this on a video? this is not happening for me

**Comment by Minacat1** [comment]
Ill try that now with a video

**Comment by Minacat1** [comment]
Maybe try to move this around to enter multiple times or send message fast or maybe try the code ??

**Comment by Minacat1** [comment]
@vroomyy

**Comment by Minacat1** [comment]
There's the screenshots not a video me is mina cat but not  virage

**Comment by Minacat1** [comment]
I did this on mobile not pc

**Comment by Minacat1** [comment]
@vroomyy

**Comment by Minacat1** [comment]
@vroomyy

**Comment by vroomyy** [comment]
its not possible to send a message as someone else, probably was a visual bug
